name: CI iOS

on:
  push:
    branches: [ main ]
    paths:
      - 'ios/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Install iOS Dependency
        run: yarn run install:ios

      - name: Run iOS tests
        run: yarn run test:ios
